# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Copy the wheel file to the VM
  config.vm.provision "file", source: "docs/dist/scistream_proto-1.1.0-py3-none-any.whl", destination: "/home/vagrant/scistream_proto-1.1.0-py3-none-any.whl"

  # Install packages and apps
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    sudo apt-get install -y iperf3
    sudo usermod -aG docker vagrant
    sudo apt-get install -y python3-pip
    pip3 install /home/vagrant/scistream_proto-1.1.0-py3-none-any.whl
  SHELL

  # Define the consumer VM
  config.vm.define :prod do |prod|
    prod.vm.box = "bento/ubuntu-22.04"

    prod.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    prod.vm.network :private_network, :ip => '192.168.110.110'
    #prod.vm.network :public_network, :ip => '192.168.121.10', :dev => 'ens18'
    #prod.vm.network :public_network, :mode => "bridge", :type => "bridge"
  end

  config.vm.define :prods do |prods|
    prods.vm.box = "bento/ubuntu-22.04"

    prods.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    prods.vm.network :private_network, :ip => '192.168.110.111'
    prods.vm.network :private_network, :ip => '192.168.120.110'
    #prod.vm.network :public_network, :ip => '192.168.121.10', :dev => 'ens18'
    #prod.vm.network :public_network, :mode => "bridge", :type => "bridge"
  end

  config.vm.define :conss do |conss|
    conss.vm.box = "bento/ubuntu-22.04"

    conss.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    conss.vm.network :private_network, :ip => '192.168.120.111'
    conss.vm.network :private_network, :ip => '192.168.130.110'
    #prod.vm.network :public_network, :ip => '192.168.121.10', :dev => 'ens18'
    #prod.vm.network :public_network, :mode => "bridge", :type => "bridge"
  end

  config.vm.define :cons do |cons|
    cons.vm.box = "bento/ubuntu-22.04"

    cons.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    cons.vm.network :private_network, :ip => '192.168.130.111'
    #prod.vm.network :public_network, :ip => '192.168.121.10', :dev => 'ens18'
    #prod.vm.network :public_network, :mode => "bridge", :type => "bridge"
  end


  # Options for Libvirt Vagrant provider.
  config.vm.provider :libvirt do |libvirt|

    # A hypervisor name to access.
    libvirt.driver = "kvm"

    # The name of the server, where Libvirtd is running.
    # libvirt.host = "localhost"

    # If use ssh tunnel to connect to Libvirt.
    libvirt.connect_via_ssh = false

    # The username and password to access Libvirt. Password is not used when
    # connecting via ssh.
    libvirt.username = "vagrant"
    #libvirt.password = "secret"

    # Libvirt storage pool name, where box image and instance snapshots will
    # be stored.
    libvirt.storage_pool_name = "default"

    # Set a prefix for the machines that's different than the project dir name.
    #libvirt.default_prefix = ''
  end
end
