# files from:
# scp vagrant@192.168.20.11:/home/vagrant/.local/lib/python3.10/site-packages/src/services/stunnel/Dockerfile ./vag-vm-files/Dockerfile.4


## docker build -t stunnel-image .
FROM alpine:latest
RUN set -x \
 && addgroup -S stunnel \
 && adduser -S -G stunnel stunnel \
 && apk add --update --no-cache \
        ca-certificates \
        libintl \
        openssl \
        stunnel

RUN mkdir -p /etc/stunnel \
 && chown -R stunnel:stunnel /etc/stunnel

USER stunnel
EXPOSE 443
CMD ["stunnel"]
