##### Commented

# NGINX configuration of the stream module which is used for 
# handling TCP/UDP traffic, which is different from NGINX’s 
# HTTP module that handles web traffic

worker_processes auto;          # sets the number of worker processes to handle the traffic
                                # NGINX automatically determine the optimal number of
                                # worker processes based on the number of CPU cores available.

events { }                      # Configuring event-related settings for handling connections
                                # Empty block means default settings are used

stream {                        # Configuring the stream module. Handling TCP or UDP streams
    server {
        listen 5002;            # Listening on port 5002
        proxy_pass 192.168.0.26:7000;       # Forwarding the incoming traffic to the specified
                                            # IP address and port

    }
}

# This configuration allows NGINX to forward TCP traffic received on port 5002
# to a backend server at 192.168.0.26 on port 7000. This setup is often used
# for applications that require TCP/UDP load balancing or proxying, such as
# database connections or other non-HTTP services.